Pull request #3: [AIR-7351] Reshape bias into 1 dimension in fullyconnected OP
Merge in AITEC/vela from feature/AIR-7351-vela-model-compiling-failed-axes-match-error to imx_3.3.0

Squashed commit of the following:

commit cded13c2c5f8fe21b06c5afe0d6f0b41d59cad11
Author: Jiwei Fu <jiwei.fu@nxp.com>
Date:   Tue Jul 26 19:52:56 2022 +0800

    [AIR-7351] Reshape bias into 1 dimension in fullyconnected OP

    Fix below error:
    tens.values = tens.values.transpose(reorder)
    ValueError: axes don't match array

    Signed-off-by: Jiwei Fu <jiwei.fu@nxp.com>